config/routes.rb
Rails.application.routes.draw do
  root to: "restaurants#index"
  devise_for :users
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]
  # all of our top restaurant
  # get '/restaurants/top', to: 'restaurants#top', as: :top_restaurants
  # see a chef page for a specific restaurant
  # get '/restaurants/:id/chef', to: 'restaurants#chef', as: :restaurant_chef
end

# Custom Non-CRUD routes
# collection  -> about all of the restaurants (aka no ID)
# member      -> one specific restaurant (aka need ID)


# collection do
#   get 'top'
# end
# member do
#   get 'chef'
# end

# get restaurants_path
# post restaurants_path

# get restaurant_path(restaurant)
# path restaurant_path(restaurant)
# delete restaurant_path(restaurant)

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # associations
  # dependent: :destroy -> destroy other instances that are dependent on it
  has_many :reviews, dependent: :destroy # creates a method restaurant.reviews
  belongs_to :user
  # validations
  # validates :column_name, whatever_validation
  validates :name, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  # associations
  belongs_to :restaurant # creates a method review.restaurant
  # validations
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :restaurants, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # '/restaurants/top'
  def top
    @restaurants = Restaurant.where(rating: 5)
  end

  # '/restaurants/52/chef'
  def chef
    @restaurant = Restaurant.find(params[:id])
    # @chef_name = @restaurant.chef_name
  end

  # '/restaurants'
  def index
    @restaurants = Restaurant.all
    # render 'index.html.erb'
  end

  # '/restaurants/1'
  def show
    @restaurant = Restaurant.find(params[:id])
  end

  # '/restaurants/new'
  def new
    # just for the form builder
    @restaurant = Restaurant.new
  end

  # to get to this action, i have to submit a form -> post /restaurants
  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      # if it saves, go to the show page
      redirect_to restaurant_path(@restaurant)
    else
      # show the form again with the restaurant that didnt save
      render 'new', status: :unprocessable_entity
    end
  end

  # '/restaurants/2/edit'
  def edit
    # is just for the form
    @restaurant = Restaurant.find(params[:id])
  end

  # to get to this action, i have to submit a form -> patch /restaurants/1
  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      # if it saves, go to the show page
      redirect_to restaurant_path(@restaurant)
    else
      # show the form again with the restaurant that didnt save
      render 'edit', status: :unprocessable_entity
    end
  end

  # to get to this action, we have to click a button -> delete
  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path, status: :see_other
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:rating, :name, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  # '/restaurants/52/reviews/new'
  def new
    # only for the form (we need both the review AND restaurant)
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  # we have to submit a form to get here -> post restaurants/52/reviews
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      raise
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurants2058</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_card.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path "#{restaurant.category.downcase}.jpg" %>);">
  <%= image_tag "https://kitt.lewagon.com/placeholder/users/#{restaurant.user.username}", class: "avatar" %>
  <%= link_to restaurant.name, restaurant_path(restaurant), class: 'text-decoration-none text-white' %>
</div>

app/views/restaurants/_form.html.erb
<%# Simple Form shortcut -> sf + tab %>
<%= simple_form_for restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category %>
  <%= f.input :rating, collection: (1..5) %>
  <%= f.submit 'Submit', class: 'btn btn-primary mt-3' %>
<% end %>

app/views/restaurants/_side_info.html.erb
<p class="fw-lighter opacity-75">
  <i class="fas fa-map-pin"></i><span class='ms-2'><%= @restaurant.address %></span>
</p>
<p class="fw-lighter opacity-75">
  <% rand(2..5).times do %>
    <i class="fas fa-dollar-sign"></i>
  <% end %>
</p>
<p class="fw-lighter opacity-75">
  <i class="fas fa-utensils"></i><span class='ms-2'><%= @restaurant.category %></span>
</p>
<p class="fw-lighter">
  <i class="fas fa-user"></i><span class='ms-2'><%= @restaurant.user.username %></span>
  <%= image_tag "https://kitt.lewagon.com/placeholder/users/#{@restaurant.user.username}", class: "avatar", style: "width:40px; height:40px; border-radius:50%; object-fit:cover; border:2px solid #fff; box-shadow:0 2px 8px rgba(0,0,0,0.15);" %>
</p>
<div class="d-flex">
  <!-- edit and delete here-->
  <p>
    <%= link_to edit_restaurant_path(@restaurant), class: 'text-dark text-decoration-none' do %>
      <i class="fas fa-pencil-alt mx-1"></i>
    <% end %>
    <%= link_to restaurant_path(@restaurant), class: 'text-dark text-decoration-none', data: { turbo_method: :delete, turbo_confirm: "Do you want to delete #{@restaurant.name}" } do %>
      <i class="fas fa-trash mx-1"></i>
    <% end %>
  </p>
</div>

app/views/restaurants/chef.html.erb
<div class="container">
  <h1><%= @restaurant.chef_name %></h1>
  <p>Works at: <%= @restaurant.name %></p>
  <%= link_to 'Back to restaurant', restaurant_path(@restaurant), class: 'btn btn-secondary'  %>
</div>

app/views/restaurants/edit.html.erb
<div class="container">
  <h1>Edit Restaurant</h1>
  <%= render 'restaurants/form', restaurant: @restaurant %>
</div>

app/views/restaurants/index.html.erb
<div class="container mt-3">
  <div class="d-flex justify-content-between align-items-center">
    <h1>Restaurants</h1>
    <%= link_to "+", new_restaurant_path, class: 'btn btn-secondary'  %>
  </div>
  <div class="cards">
    <% @restaurants.each do |restaurant| %>
      <%= link_to restaurant_path(restaurant), class: 'text-white text-decoration-none' do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
          <%= restaurant.name %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1>Add a Restaurant</h1>
  <%= render 'restaurants/form', restaurant: @restaurant %>
</div>

app/views/restaurants/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path "#{@restaurant.category.downcase}.jpg" %>);">
  <div class="container">
  </div>
</div>
<div class="container mt-2 mb-5">
  <div class="row justify-content-around">
    <div class="col-12 col-sm-8">
      <p>
        <%= link_to '< Restaurants', restaurants_path, class: 'btn-light opacity-25 text-decoration-none' %>
      </p>
      <div class="d-flex align-items-center">
        <h1 class="m-0"><%= @restaurant.name %></h1>
        <p class="m-0 ms-2" style="font-size: 0.8em">
          <% @restaurant.rating.round.times do %>
            <i class="fas fa-star"></i>
          <% end %>
          <% (5 - @restaurant.rating.round).times do %>
            <i class="far fa-star"></i>
          <% end %>
        </p>
      </div>
      <p class="fw-lighter opacity-75 mt-2"><%= Faker::Restaurant.description  %></p>
      <h3>
        Reviews
        <%= link_to '+', new_restaurant_review_path(@restaurant)  %>
      </h3>
      <ul>
        <% if @restaurant.reviews.any? %>
          <% @restaurant.reviews.each do |review| %>
            <li>
              <%= review.content %>
              <%= link_to 'x', review_path(review), class: 'text-decoration-none text-gray', data: { turbo_method: :delete, turbo_confirm: 'Delete this review?' } %>
            </li>
          <% end %>
        <% else %>
          <li>No reviews yet.</li>
        <% end %>
      </ul>
    </div>
    <div class="col-12 col-sm-4 mt-5">
      <%= render 'restaurants/side_info' %>
    </p>
  </div>
</div>

app/views/restaurants/top.html.erb
<div class="container mt-3">
  <div class="d-flex justify-content-between align-items-center">
    <h1>5 Star Restaurants</h1>
    <%= link_to new_restaurant_path, class: 'text-dark text-decoration-none' do %>
      <i class="fa-solid fa-plus"></i>
    <% end %>
  </div>
  <div class="cards">
    <% @restaurants.each do |restaurant| %>
      <%= render 'restaurants/card', restaurant: restaurant %>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <h1>Add a Review for <%= @restaurant.name %></h1>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.submit "Add", class: 'btn btn-primary mt-3' %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to restaurants_path, class: "navbar-brand" do %>
      <i class="fas fa-utensils"></i>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to "Restaurants", restaurants_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/#{current_user.username}", class: "avatar", alt: "dropdown menu" %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>